apiVersion: v1
kind: Service
metadata:
  name: cell-test3d-service
  labels:
    application: cell
    app: cell
spec:
  type: NodePort
  ports:
  - name: httpport
    port: 8080
    targetPort: 8080
    nodePort: 31622
  - name: metricsport
    port: 8081
    targetPort: 8080
    nodePort: 30731
    protocol: TCP
  selector:
    svc: cell-test3d-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-test3d-service
  labels:
    application: cell
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: cell-test3d-service
        application: cell
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: cell-test3d-service
        image: cell-test:0.1
        #image: 10.6.136.80:443/cell-test:latest
        #image: 10.6.136.50:5000/orderpick_cwl-order-service:latest
        #resources:
        #  requests:
        #    cpu: "800m"
        #    #memory: "512Mi"
        #  limits:
        #    cpu: "800m"
        #    #memory: "512Mi"
        #imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              #command:
                #- sleep
                #- "10"
              command: ["/bin/sh", "-c", "echo lxm; sleep 30"]
        ports:
        - containerPort: 8080
          name: httpport
        #livenessProbe:
        #  httpGet:
        #    path: /actuator/health
        #    port: 8080
        #  initialDelaySeconds: 40
        #  periodSeconds: 20
        #readinessProbe:
        #  httpGet:
        #    path: /actuator/health
        #    port: 8080
        #  initialDelaySeconds: 40
        #  periodSeconds: 20
        env:
          - name: SPRING_DATASOURCE_URL
            #value: jdbc:mysql://10.6.136.50:3306/cell_test
            value: jdbc:mysql://10.6.136.50:3307/cell_test
#          - name: JAVA_OPTS
#            value: "-Dsun.net.inetaddr.ttl=30"
#          - name: SPRING_DATASOURCE_URL
#            value: jdbc:mysql://cell-mysql/cwl_order_service
#          - name: SPRING_DATASOURCE_USERNAME
#            valueFrom:
#              secretKeyRef:
#                name: cell-db-secret
#                key: username
#          - name: SPRING_DATASOURCE_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                name: cell-db-secret
#                key: password
#          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
#            value: com.mysql.jdbc.Driver
#          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
#            value: cell-kafka:9092
#          - name: SERVER_PORT
#            value: "8080"
#          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
#            value: cell-zookeeper:2181
#          - name: SPRING_ZIPKIN_BASE_URL
#            value: http://cell-zipkin:9411/

  selector:
    matchLabels:
      application: cell
      svc: cell-test3d-service
---

#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: cell-test-3d-hpa
#spec:
#  maxReplicas: 1
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: cell-test3d-service
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 25
#    - type: Resource
#      resource:
#        name: memory
#        targetAverageValue: 50Mi