spring:
  output:
    ansi:
      enabled: always
  application:
    name: cell-test
  lifecycle:
    timeout-per-shutdown-phase: 400s

logging:
  level:
    root: debug
    org.apache.tomcat.util.threads.LimitLatch: debug
    #org.apache: info
    #org.hibernate: info
    #org:
      #springframework:
        #boot:
          #web: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true
    #connection-timeout: 50s
  shutdown: graceful

